import React, { useEffect, useState } from 'react'
import { Card, FormField, Loader } from '../components'


const Home = () => {

    const [loading, setLoading] = useState(false)
    const [allPosts, setAllPosts] = useState(null)
    const [searchText, setSearchText] = useState('')


    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[32px]'>
                    The Communty Showcase
                </h1>
                <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
                    Browse through a collection of imaginative and visually stunning images generated by Dall-E AI.
                </p>
            </div>
            <div className="mt-16">
                <FormField />
            </div>
            <div className="mt-10">
                {loading ? (
                    <div className="flex justify-center items-center">
                        <Loader />
                    </div>
                )
                    :
                    (
                        <>
                            {searchText }
                        </>
                    )
                }
            </div>
        </section>
    )
}

export default Home
